[package]
name = "nvptx-sys"
version = "0.0.2"
authors = ["Julia Tatz <tatz.j@northeastern.edu>"]
edition = "2018"

[dependencies]
libm = "0.2"

[features]
default = []
panic = []
alloc = []
noisy-panics = ["panic"]
fast-math = []
