[package]
name = "nvptx-sys"
version = "0.1.0"
authors = ["Julia Tatz <tatz.j@northeastern.edu>"]
edition = "2018"

[dependencies]
libm = "0.2"
nvptx-vprintf = { path = "nvptx-vprintf" }

[features]
default = []
panic = []
alloc = []
noisy-panics = ["panic"]
fast-math = []

[workspace]
members = ["nvptx-vprintf"]
